[package]
name = "dusk-contract-standards"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
dusk-core = "=1.6.0"
dusk-forge = { workspace = true, optional = true }
bytecheck = { workspace = true }
rkyv = { workspace = true, features = ["size_32", "alloc", "validation"] }
serde = { version = "1", default-features = false, features = [
    "derive",
    "alloc",
], optional = true }

[features]
contract = ["forge"]
forge = ["dep:dusk-forge"]
serde = ["dep:serde", "dusk-core/serde"]

[dev-dependencies]
dusk-vm = "=1.6.0"
rand = { workspace = true, features = ["std_rng"] }
serde_json = { version = "1", default-features = false, features = ["std"] }
